import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BottomNavigation from '../components/BottomNavigation';
import ToggleTheme from "@/components/ThemeToggle";
import {Providers} from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="fixed w-screen h-10">
          <ToggleTheme />
        </header>
        <div className="navbar">
          <BottomNavigation />
        </div>
        <main className="w-screen h-screen m-0 p-0 z-0">
          {children}
        </main>
      </body>
    </html>
  );
}
